name: Download HTML on Push

on:
  push:
    branches:
      - main  # Adjust to your main branch name if different

jobs:
  wget:
    runs-on: ubuntu-latest
    steps:
    - name: wget
      uses: wei/wget@v1




